sudo: required
dist: trusty
services:
- rabbitmq
- mongodb
language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- node scripts/fix_abroad_shrinkwrap.js
- npm install
script:
- npm run build:production
- python -m unittest
cache:
  directories:
  - $HOME/.cache/pip
  - node_modules
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
